behaviors:
    My Behavior:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1000
            buffer_size: 5000
            learning_rate: 0.00005
            beta: 0.005
            epsilon: 0.1
            lambd: 0.95
            num_epoch: 2
            learning_rate_schedule: linear
        network_settings:
            normalize: true
            hidden_units: 100
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.8
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 100000000
        time_horizon: 128
        summary_freq: 5000
        threaded: true
